---
- name: Install GitLab via bastion host
  hosts: bastion
  tasks:
    # Step 1: Install required tools on the bastion
    - name: Install required tools
      ansible.builtin.package:
        name:
          - curl
          - wget
          - apt-transport-https
          - gnupg
          - apt-rdepends
        state: present

    # Step 2: Download GitLab installation script
    - name: Download GitLab installation script
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
        dest: /tmp/gitlab-install.sh
        mode: '0755'

    # Step 3: Download GitLab EE package
    - name: Download GitLab EE package
      ansible.builtin.shell:
        cmd: apt-get download gitlab-ee
        args:
          chdir: /tmp/gitlab_packages

    # Step 4: Download GitLab dependencies
    - name: Download GitLab dependencies
      ansible.builtin.shell:
        cmd: |
          apt-rdepends curl openssh-server ca-certificates tzdata perl | grep -v "^ " | xargs -I {} apt-get download {}
        args:
          chdir: /tmp/gitlab_packages

    # Step 5: Copy packages to the private VM
    - name: Copy packages to private VM
      ansible.builtin.copy:
        src: /tmp/gitlab_packages/
        dest: /tmp/gitlab_packages/
        remote_src: no
        mode: '0755'
      delegate_to: "{{ ansible_host }}"
      vars:
        ansible_host: "{{ private_vm_ip }}"

    # Step 6: Copy GitLab installation script to the private VM
    - name: Copy GitLab installation script
      ansible.builtin.copy:
        src: /tmp/gitlab-install.sh
        dest: /tmp/gitlab-install.sh
        remote_src: no
        mode: '0755'
      delegate_to: "{{ ansible_host }}"
      vars:
        ansible_host: "{{ private_vm_ip }}"

- name: Install GitLab on the private VM
  hosts: private_vm
  tasks:
    # Step 7: Install GitLab on private VM
    - name: Run GitLab installation script
      ansible.builtin.shell:
        cmd: |
          sudo /tmp/gitlab-install.sh
          sudo dpkg -i /tmp/gitlab_packages/*.deb || sudo apt-get -f install -y
          sudo EXTERNAL_URL="http://{{ ansible_host }}" gitlab-ctl reconfigure