---
- name: Install GitLab via bastion host
  hosts: bastion
  become: yes  # Elevate privileges for tasks in this play
  tasks:
    # Step 1: Update the package cache
    - name: Update the package cache
      ansible.builtin.apt:
        update_cache: yes

    # Step 2: Install required tools on the bastion
    - name: Install required tools
      ansible.builtin.package:
        name:
          - curl
          - wget
          - apt-transport-https
          - gnupg
        state: present

    # Step 3: Add the GitLab package repository
    - name: Add GitLab repository
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash

    # Step 4: Create directory for GitLab packages
    - name: Create directory for GitLab packages
      ansible.builtin.file:
        path: /tmp/gitlab_packages
        state: directory
        mode: '0755'

    # Step 5: Download GitLab installation script
    - name: Download GitLab installation script
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
        dest: /tmp/gitlab-install.sh
        mode: '0755'

    # Step 6: Download GitLab EE package
    - name: Download GitLab EE package
      ansible.builtin.shell:
        cmd: apt-get download gitlab-ee
        chdir: /tmp/gitlab_packages

    # Step 7: Download GitLab dependencies
    - name: Download GitLab dependencies
      ansible.builtin.shell:
        cmd: |
          apt-get download curl openssh-server ca-certificates tzdata perl
        chdir: /tmp/gitlab_packages

    # Step 8: Copy packages to the private VM
    - name: Copy packages to private VM
      ansible.builtin.copy:
        src: /tmp/gitlab_packages/
        dest: /tmp/gitlab_packages/
        remote_src: no
        mode: '0755'
      delegate_to: "{{ ansible_host }}"
      vars:
        ansible_host: "{{ private_vm_ip }}"

    # Step 9: Copy GitLab installation script to the private VM
    - name: Copy GitLab installation script
      ansible.builtin.copy:
        src: /tmp/gitlab-install.sh
        dest: /tmp/gitlab-install.sh
        remote_src: no
        mode: '0755'
      delegate_to: "{{ ansible_host }}"
      vars:
        ansible_host: "{{ private_vm_ip }}"

- name: Install GitLab on the private VM
  hosts: private_vm
  become: yes  # Elevate privileges for tasks in this play
  tasks:
    # Step 10: Install GitLab on private VM
    - name: Run GitLab installation script
      ansible.builtin.shell:
        cmd: |
          sudo /tmp/gitlab-install.sh
          sudo dpkg -i /tmp/gitlab_packages/*.deb || sudo apt-get -f install -y
          sudo EXTERNAL_URL="http://{{ ansible_host }}" gitlab-ctl reconfigure

    # Step 11: Check GitLab status
    - name: Check GitLab service status
      ansible.builtin.shell:
        cmd: gitlab-ctl status
      register: gitlab_status

    # Step 12: Display GitLab status
    - name: Display GitLab status
      ansible.builtin.debug:
        msg: "{{ gitlab_status.stdout }}"